### PR TITLE
Fix issue #54

### PR DESCRIPTION
**Pull request by bambinoua**
This PR will fix the problem with icon font tree shaking. The `iconMap` removed as redundant.

изображение

https://github.com/ziofat/material_design_icons_flutter/assets/45417992/59b04b52-017d-4f52-8b14-4fc5686d2878

### CODE REVIEW

**Comment by dickermoshe** [comment]
This is a breaking change as this is no longer const.

**Comment by bambinoua** [comment]
> This is a breaking change as this is no longer const.

What do you mean?

```dart
class MdiIcons {
  const MdiIcons();

  static const _values = <String, IconData>{ // _values are constant map
    'abTesting': _MdiIconData(0xf01c9),
    ...,
    'zodiacVirgo': _MdiIconData(0xf0a88),
  }

  static IconData get abTesting => _values['abTesting']!; // getter returns the constant value
  ...
  static IconData get zodiacVirgo => _values['zodiacVirgo']!;
}
```

**Comment by bambinoua** [comment]
> This is a breaking change as this is no longer const.

I catched the problem. But actually they a **const** because getters return values **from a constant list**.

**Comment by ziofat** [comment]
I have verified this PR and it works. Thanks for your contributing.
It now have some conflicts with another PR just merged in, could you please rebase the main branch? Thanks.

**Comment by bambinoua** [comment]
> could you please rebase the main branch?

Do you mean for syncing? If yes, I've just done this.

**Comment by ziofat** [comment]
Cool, that's it.

**Comment by bambinoua** [comment]
Hi, @ziofat.

After try to implement new version of this packages (actually mine PR) I have to admit that my version is not as good as it seemed.

The main problem I met is that it is impossible to create a `const` structures which use `MdiIcons`.

Here it is an example:
```dart
class Option {
  const Option(this.icon);

  final IconData icon;
}

// Here I can create  only a final [options] variable but not const
final options = <Option>[ 
  Option(MdiIcons.abTesting),
];

```
In my code I have many variable like this:
```dart
class EnumClass {
  static const _icons = <IconData>[
    MdiIcons.x,
    MdiIcons.y,
    ...
  ];
}
```
Now I need convert the to `final`.

And I'm confused by the thought of the behavior of widgets similar to `Icon` or which use the `IconData` parameter which cannot be declared as `const` now. As we know `const` widgets are declared on _compile time_ and not refreshed on each `build` but now I am not sure if such behaviour will stay as it was.

What do you think? Should the last PR be reverted and PR #57 applied.

**Pull request merged**
